feat: api routes for EvmApi
ethereum-boilerplate/ethereum-boilerplate pull request #176
Opened 2022-08-27 10:27 UTC by johnvsnagendra

Suggestion to add separate api routes for each EvmAPI endpoint. 

The following files contain param types and nextjs API routes for the functions under `EvmApi.account`. 

By defining separate API routes for each EvmAPI endpoint, we can reuse them when calling from ClientSide or ServerSide use. 

Let me know your opinion on this suggestion.🙌

2022-08-27 10:30 UTC, Y0moo commented
Hey @johnvsnagendra! We will release a library with API routes and hooks to call Moralis APIs from client-side

2022-08-27 10:30 UTC, Y0moo commented
coming 2 weeks

2022-08-27 10:34 UTC, Y0moo approved these changes

2022-08-27 10:34 UTC, Y0moo commented on src/types/EvmApi/account/types.ts
> +// Account API Param Types
Love this work with types. GJ on this

2022-08-27 10:38 UTC, Y0moo requested changes

2022-08-27 10:38 UTC, Y0moo commented on pages/api/EvmApi/account/getNFTTransfers.ts
> +      address: req.body.address,
What'd say about destructurization like this here instead?
```
const { address, chain, providerUrl, toBlock } = req.body;
const data = await Moralis.EvmApi.account.getNativeBalance({ address, chain, providerUrl, toBlock });
```

2022-08-27 11:20 UTC, johnvsnagendra commented on src/types/EvmApi/account/types.ts
> +// Account API Param Types
Glad you liked it. 
Do you think I should continue creating these API routes for other endpoints? If not, I can continue with the types, which I believe will be helpful even with the API routes library release.

2022-08-27 11:20 UTC, johnvsnagendra commented on pages/api/EvmApi/account/getNFTTransfers.ts
> +      address: req.body.address,
Sure. I will make the required changes.

2022-08-27 11:35 UTC, johnvsnagendra commented on pages/api/EvmApi/account/getNFTTransfers.ts
> +      address: req.body.address,
I have refreshed the files with the requested changes. You can check now.🙌

2022-08-30 13:57 UTC, Y0moo commented on src/types/EvmApi/account/types.ts
> +// Account API Param Types
@johnvsnagendra thanks. No need for manual writing them

2022-08-31 03:43 UTC, closed without merging